language: rust

rust:
  - 1.24.0              # minimum supported toolchain
  - nightly-2018-07-24  # pinned toolchain for clippy
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - CLIPPY_RUST_VERSION=nightly-2018-07-24

before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$CLIPPY_RUST_VERSION" ]]; then
      rustup component add clippy-preview;
    fi'

script:
  - cargo test
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$CLIPPY_RUST_VERSION" ]]; then
      cargo clippy -- -D warnings;
    fi'
